device: 'cuda'

model:
    vocab_size: 50257
    context_length: 1024
    drop_rate: 0.1
    qkv_bias: True
    param_count: "1558M"
    emb_dim: 1600
    n_layers: 48
    n_heads: 25
    model_weights_path: gpt2

data:
    split: null
    max_length: 256
    batch_size: 16
    include_reason: False

train:
    epochs: 10
    learning_rate: 0.0001
    weight_decay: 0.01
    eval_step: 750
    grad_accum_steps: 2
    clip_grads: False
    max_grad: 1.0
